version: '3'

services:
  website:
    build: .
    command: bash start.sh
    ports: 
      - '3000:3000'
    volumes:
      - '.:/vue_example'
      - 'box:/box'

  box:
    image: busybox
    volumes:
      - '.:/box'

volumes:
  box: