version: '2'

services:
  website:
    build: .
    command: bash start.sh
    ports: 
      - '3000:3000'
    volumes:
      - '.:/vue_example'
    volumes_from:
      - box

  box:
    image: busybox
    volumes:
      - /box

volumes:
  box: